# Generated by Django 4.2.2 on 2023-06-12 08:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=40)),
                ("last_name", models.CharField(db_index=True, max_length=40)),
                ("middle_name", models.CharField(max_length=40, null=True)),
                ("photo", models.ImageField(upload_to="photos/employees")),
                ("position", models.CharField(max_length=255)),
                ("salary", models.DecimalField(decimal_places=2, max_digits=20)),
                ("age", models.PositiveSmallIntegerField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "department",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name"],
            },
        ),
    ]
